### Create a new user
POST https://floating-scrubland-41388.herokuapp.com/auth/signup
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}

### Signin as an existing user
POST https://floating-scrubland-41388.herokuapp.com/auth/signin
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "12345678"
}

### Get the currently signed in user
GET https://floating-scrubland-41388.herokuapp.com/auth/whoami

### Sign out
POST http://localhost:3000/auth/signout

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users with a given email
GET http://localhost:3000/auth?email=asdf@asdf.com

### Delete a user with a given ID
DELETE http://localhost:3000/auth/1

### Update a user with a given ID
PATCH  http://localhost:3000/auth/3
Content-Type: application/json

{
  "password": "bbbbbbb"
}
